version: '3.8'

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "gamebioss_traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9000"
      - "--entrypoints.rtmp.address=:9935"
      - "--entrypoints.dashboard.address=:9001"
    ports:
      - "9000:9000"       
      - "9935:9935"   
      - "9001:9001" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: gameboss_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=streamuser
      - POSTGRES_PASSWORD=streampassword
      - POSTGRES_DB=streamdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamuser -d streamdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: gameboss_django_backend
    volumes:
      - ./backend:/app 
      - ./media:/media:ro 
    environment:
      - DB_NAME=streamdb
      - DB_USER=streamuser
      - DB_PASS=streampassword
      - DB_HOST=db
      - SECRET_KEY=your-super-secret-key-change-me
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`18.225.19.45`)"
      - "traefik.http.routers.gboss-backend.pathprefix=/api"
      - "traefik.http.routers.gboss-backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=10"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    restart: unless-stopped

  srs:
    image: ossrs/srs:4
    container_name: gameboss_srs_media_server
    volumes:
      - ./srs_config/srs.conf:/usr/local/srs/conf/srs.conf 
      - ./media:/usr/local/srs/objs/nginx/html 
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.srs-rtmp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.srs-rtmp.entrypoints=rtmp"
      - "traefik.tcp.services.srs-rtmp.loadbalancer.server.port=1935"
      - "traefik.http.routers.srs-hls.rule=Host(`18.225.19.45`) && (PathPrefix(`/live/`) || PathPrefix(`/record/`))"
      - "traefik.http.routers.gboss-srs-hls.entrypoints=web"
      - "traefik.http.routers.srs-hls.priority=10" 
      - "traefik.http.services.srs-hls.loadbalancer.server.port=8080"
    command: ./objs/srs -c conf/srs.conf
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: gameboss_nextjs_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
      - /app/.next
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`18.225.19.45`)"
      - "traefik.http.routers.gboss-srs-hls.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1" 
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://18.225.19.45:9000/api
    restart: unless-stopped

volumes:
  postgres_data: