# Generated by Django 5.2.4 on 2025-07-15 07:06

import django.db.models.deletion
import streams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream_key', models.CharField(default=streams.models.generate_stream_key, max_length=30, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('hls_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
