# Generated by Django 5.2.4 on 2025-07-16 11:54

import streams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(default=streams.models.generate_stream_key, max_length=32, unique=True),
        ),
    ]
