# Generated by Django 5.2.4 on 2025-07-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_alter_stream_stream_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='recorded_url',
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='streams.stream')),
            ],
        ),
    ]
